### ISSUE TITLE
Should I consider this project inactive?

### ISSUE THREAD

**Issue by hasusuf** [negronjl/terraform-provider-maas#15]
Since the last changes to the project were ~ 4 years ago. Should I consider this project inactive then?

If yes do you can you suggest an alternative?

**Comment by BrandonHarrisonCode** [comment]
It looks like the most up to date (but still apparently inactive) fork is from [Roblox](https://github.com/Roblox/terraform-provider-maas). It looks like @suchpuppet has created a fork with a manifest to publish to the [terraform registry](https://registry.terraform.io/providers/suchpuppet/maas/latest) as well.

**Comment by suchpuppet** [comment]
I forked it from Roblox so that it could be published to the Terraform registry rather than have to install as a local plugin in pipelines.  I am planning on fixing a few things in the near future but have not had the time recently.  There are some problematic behaviors with data sources at the moment.

**Comment by hasusuf** [comment]
Sweet! Thanks, guys! 👍

**Comment by Yasumoto** [comment]
@robloxrob @negronjl @suchpuppet would y'all be interested in taking on another maintainer or two? I'm planning to use this to consolidate several VMs we have and would be happy to help pitch in if that makes it easier.

While maintaining providers like this is obviously a full-time job on its own (that likely none of us have time for 😛 ) it'd be great to make it a little clearer for folks to know where to send PRs and keep up with maas as it changes over time. Definitely no pressure, but figured we should at least try it out!

**Comment by robloxrob** [comment]
That would be great. Happy to give code reviews. We mostly use the provider as is today, but we had outsourced most of the code work on it. We no longer have that team working on it, so any further development would be appreciated.

**Comment by Yasumoto** [comment]
So proposal: we make [Roblox/terraform-provider-maas](https://github.com/Roblox/terraform-provider-maas) the new "main" repo. Unless there's strong opposition, I think there are three things to do here:

1. Looks like we'll need to file a support request to get [Roblox/terraform-provider-maas](https://github.com/Roblox/terraform-provider-maas) unforked. @robloxrob could you take point here (again, in your copious free time 😅 )
2. @suchpuppet looks like you'll have a diff to merge back into that new repo?
3. @robloxrob I think this one is back on you, would you be interested in publishing [to the Terraform Registry](https://www.terraform.io/docs/registry/modules/publish.html#publishing-a-public-module)?

Also open to other ideas! Thanks for all the hard work on this so far, folks! 🙇🏼

**Comment by negronjl** [comment]
I can transfer the repo to whomever is going to maintain it.

Let me know how you all want to proceed.

Juan

**Comment by Yasumoto** [comment]
Woo! That’d be amazing! Mind adding myself, @suchpuppet , and @robloxrob ? If other folks should be added we can grant maintainership too. (And of course if folks want to be removed that’s a-okay too)

**Comment by robloxrob** [comment]
Happy to add you to the Roblox one as well. I want to do whatever to keep this product growing. Tagging @shishir-a412ed who helps lead our OSS efforts.

**Comment by negronjl** [comment]
> Woo! That’d be amazing! Mind adding myself, @suchpuppet , and @robloxrob ? If other folks should be added we can grant maintainership too. (And of course if folks want to be removed that’s a-okay too)

added all three of you

**Comment by robloxrob** [comment]
Thank you

**Comment by Yasumoto** [comment]
Thanks so much folks!

**Comment by Yasumoto** [comment]
So long as folks are good with #16 (I'm open to other approaches, but that should make sure the authors retain credit!), then I think we should close this once #16 gets merged! 🥳

**Comment by negronjl** [comment]
#16 Works for me.

**Comment by Yasumoto** [comment]
Ah, looks like we'll actually need to create a proper `GitHub Organization` for this, since we won't be able to share access to publishing on [the terraform registry](https://registry.terraform.io/publish/provider/github/negronj).

@negronjl would you be okay if we moved this repo into a new organization, maybe called `terraform-maas` ? That way anyone who comes back here will automatically get redirected to the shiny new repository. We did similar for [soto-project/soto](https://github.com/soto-project/soto) which worked out really well! 🎉

**Comment by negronjl** [comment]
👍

**Comment by Yasumoto** [comment]
Dropped a note in the [upstream MAAS discourse](https://discourse.maas.io/t/maas-terraform-provider/1255/11?u=yasumoto7) to see if anyone has other suggestions. I'm leaning toward `terraform-maas-community` as the org name unless upstream wants to bring this closer. I think we can/should get this moved by early next week to give folks a chance to comment.

Thanks again, folks!

**Comment by Yasumoto** [comment]
Great news! Looks like [Canonical is interested in helping maintain a provider](https://discourse.maas.io/t/maas-terraform-provider/1255/13?u=yasumoto7), which is at [ionutbalutoiu/terraform-provider-maas](https://github.com/ionutbalutoiu/terraform-provider-maas).

I'm not tied to a specific repo being the "base" but if anyone has a preference please comment on the Discourse thread!

**Comment by robloxrob** [comment]
Awesome!

**Comment by Yasumoto** [comment]
Hi pals! Sorry for the silence here!

I've been working on a few other things, but just to keep everyone updated I think these are the next steps:

1. Review [ionutbalutoiu/terraform-provider-maas](https://github.com/ionutbalutoiu/terraform-provider-maas) to compare functionality.
2. Post on the [Discourse thread](https://discourse.maas.io/t/maas-terraform-provider/1255/13?u=yasumoto7) our analysis about what we think the best project to support going forward is.
3. Maybe have a vote or something, then we can start fixing up + adding functionality to the provider!

I should have time again in the next few weeks, but that should be enough to let someone pick this up if they have time before then!

**Comment by Yasumoto** [comment]
Alright, looks like upstream [has decided to bring in the other provider](https://discourse.maas.io/t/maas-terraform-provider/1255/19) and it lives at https://github.com/maas/terraform-provider-maas. I'm going to toss up a PR to mark this deprecated and point folks there.

If anyone wants to maintain this for some reason, feel free to reject that PR and keep this going instead!

/cc @sparkiegeek @ionutbalutoiu @cpg1111 (thanks for all the hard work on the other one!)
